### ISSUE TITLE
Fix "similar-code" issue in dns_information/ns_info_test.go

### ISSUE THREAD

**Issue by careyjames** [careyjames/dns-scout#46]
Similar blocks of code found in 2 locations. Consider refactoring.

https://codeclimate.com/github/careyjames/dns-scout/dns_information/ns_info_test.go#issue_65428f01e0cf760001000067

**Comment by TusharGupta01** [comment]
for this, we need to remove test files from code analysis. test files will have duplicates as we test many similar scenarios.
